adds api layer for patient service (#669)
* feat: add patientCreated command

* feat: add bedAssigned command

* feat: add bedUnassigned command

* feat: add patientDischarged command

* feat: add updatePatient command

* feat: add readmitPatient command

* feat: add tests

* feat: add assignUnassign tests

* cleanup

* fix: updatedAt

* fix: remove unnecessary args

* feat: getPatientById

* feat: add proto

* feat: getPatientById

* feat: create and updatePatient endpoint

* feat: assign and unassignBed

* feat: discharge and readmitPatient

* make protos

* fix: imports

* feat: getPatientById

* remove tables

* feat: getRecentPatients and tracking

* add tests

* cleanup

* fix: linting

* update ci step

* apply review changes

* maybe fix

* Merge branch 'main' into issue/635-patient-api

* protos and ci

* fix: remove duplicate version

* apply review changes

diff --git a/.github/workflows/migrations.yaml b/.github/workflows/migrations.yaml
--- a/.github/workflows/migrations.yaml
+++ b/.github/workflows/migrations.yaml
@@ -156,9 +156,18 @@ jobs:
         id: collect-version
         run: |
           echo -n "VERSION=" > $GITHUB_OUTPUT
+
           # for some reason, beyond my comprehension,
           # the output of migrate is sent to stderr in the CI, but stdout on local
-          ./migrate.sh $svc version 2>&1 | tail -n1 >> $GITHUB_OUTPUT
+          version_output=$(./migrate.sh $svc version 2>&1 | tail -n1)
+    
+          # Check if the version_output is a number
+          if [[ $version_output =~ ^[0-9]+$ ]]; then
+            echo $version_output >> $GITHUB_OUTPUT
+          else
+            echo "Error: Version is not a number: $version_output" >&2
+            echo "0" >> $GITHUB_OUTPUT
+          fi
       - name: Check version
         run: |
           ./migrate.sh $svc desired
